Revert "overflow.h: Add allocation size calculation helpers"
In file included from ../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/drivers/input/misc/uinput.c:42:
../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/include/linux/overflow.h:290:35: error: redefinition of 'array_size'
static inline __must_check size_t array_size(size_t a, size_t b)
                                  ^
../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/include/linux/overflow.h:217:35: note: previous definition is here
static inline __must_check size_t array_size(size_t a, size_t b)
                                  ^
../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/include/linux/overflow.h:312:35: error: redefinition of 'array3_size'
static inline __must_check size_t array3_size(size_t a, size_t b, size_t c)
                                  ^
../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/include/linux/overflow.h:239:35: note: previous definition is here
static inline __must_check size_t array3_size(size_t a, size_t b, size_t c)
                                  ^
../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/include/linux/overflow.h:324:35: error: redefinition of '__ab_c_size'
static inline __must_check size_t __ab_c_size(size_t n, size_t size, size_t c)
                                  ^
../../../../../../../../../home/flintman/source/ever-r/kernel/moto/sdm632/include/linux/overflow.h:251:35: note: previous definition is here
static inline __must_check size_t __ab_c_size(size_t n, size_t size, size_t c)
                                  ^
3 errors generated.
make[4]: *** [/home/flintman/source/ever-r/kernel/moto/sdm632/scripts/Makefile.build:342: drivers/input/misc/uinput.o] Error 1
make[3]: *** [/home/flintman/source/ever-r/kernel/moto/sdm632/scripts/Makefile.build:656: drivers/input/misc] Error 2

This reverts commit fa1959b1d086232d9481606a434367884f610359.