sound: tas2560-core: silence unused var
kernel/motorola/sdm632/sound/soc/codecs/tas2560-core.c:463:33: error: variable 'ret' set but not used [-Werror,-Wunused-but-set-variable]
        int nBitRate = -1, value = -1, ret = 0;

Signed-off-by: vulkan-ops <vulkanops@gmail.com>